### ISSUE TITLE
Cannot find custom operator rpn_fpn_ohem

### ISSUE THREAD

**Issue by zhengyi2015mi** [deepinsight/mxnet-SSH#1]
When I run test_ssh.py, the code occurs the following error:
![image](https://user-images.githubusercontent.com/12168094/43444380-271fb964-94d6-11e8-821f-413115647eda.png)

And the folloing is in e2e-symbol.json:
![image](https://user-images.githubusercontent.com/12168094/43444494-6f0a27c8-94d6-11e8-9fed-11d4db1cb78e.png)

**Comment by nttstar** [comment]
ohem layer should not be existing in pretrained-model.

**Comment by nttstar** [comment]
try to use this new pretrained model:  [https://pan.baidu.com/s/1wjgc227L-pPhdwunk948DA](https://pan.baidu.com/s/1wjgc227L-pPhdwunk948DA)

**Comment by zhengyi2015mi** [comment]
How do you set up epoch_end_callback  variable in train_ssh.py line 164 . I set epoch_end_callback = callback.do_checkpoint(prefix, means, stds). And it will occurs the above error in the test process with the saved model.

**Comment by nttstar** [comment]
I modified the output symbol.

**Comment by zhengyi2015mi** [comment]
Do you modify the output symbol by hand, without automatic code ?

**Comment by nttstar** [comment]
check my code
