### ISSUE TITLE
cudaMalloc failed: out of memory

### ISSUE THREAD

**Issue by Cjiangbpcs** [deepinsight/mxnet-SSH#17]
anybody bumped into this 'out of memory' error when run test_ssh.py? any suggestions would be appreciated!

python3 test_ssh.py --dataset_path=/data/face_detector/widerface/ --prefix=/data/face_detecto
r/mxnet-SSH/vgg16 --gpu 0

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `f
loat` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:root:Called with argument: Namespace(dataset='widerface', dataset_path='/data/face_detector/widerface/', epoch=0, gpu=0, has_
rpn=True, image_set='val', network='ssh', output='data/output', prefix='/data/face_detector/mxnet-SSH/vgg16', proposal='rpn', pyra
mid=False, root_path='data', shuffle=False, thresh=0.05, vis=False)
test with Namespace(dataset='widerface', dataset_path='/data/face_detector/widerface/', epoch=0, gpu=0, has_rpn=True, image_set='v
al', network='ssh', output='data/output', prefix='/data/face_detector/mxnet-SSH/vgg16', proposal='rpn', pyramid=False, root_path='
data', shuffle=False, thresh=0.05, vis=False)
[19:53:50] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[19:53:50] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
means [103.939 116.779 123.68 ]
===================> 000
===================> 111
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mxnet/symbol/symbol.py", line 1513, in simple_bind
    ctypes.byref(exe_handle)))
  File "/usr/local/lib/python3.5/dist-packages/mxnet/base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [19:53:51] src/storage/./pooled_storage_manager.h:108: cudaMalloc failed: out of memory

**Comment by Cjiangbpcs** [comment]
@nttstar could you provide some insights?

**Comment by nttstar** [comment]
gpu card info and input size?

**Comment by Cjiangbpcs** [comment]
@nttstar, all the git cloned scripts kept unchanged, for example, image_size = (2400, 2400) in test_ssh.py

gpu card info looks like this:

nvidia-smi
Mon Feb 18 18:27:50 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:17:00.0 Off |                  N/A |
| 25%   25C    P8     7W / 250W |   3637MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:65:00.0 Off |                  N/A |
| 20%   43C    P8    17W / 250W |   3208MiB / 11176MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      6523      C   /usr/bin/python3                            3627MiB |
|    1      6523      C   /usr/bin/python3                            1817MiB |
|    1      7240      C   /usr/bin/python3                            1381MiB |
+-----------------------------------------------------------------------------+

**Comment by Cjiangbpcs** [comment]
things I have tried, but did not help: 

config.TRAIN.BATCH_ROIS = 1  from 128, 64, 32, 16

Thanks.

**Comment by nttstar** [comment]
reduce your input size

**Comment by Cjiangbpcs** [comment]
@nttstar , I have tried: 

1. image_size = (1200, 1200) in test_ssh.py: out of memory;
2. image_size = (640, 640) in test_ssh.py: mxnet.base.MXNetError: [00:42:21] src/operator/nn/../tensor/../elemwise_op_common.h:123: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node  at 0-th output: expected [4096,25088], got [4096,430592]

any tips? Thanks.

**Comment by Cjiangbpcs** [comment]
image_size=(208,208) seems to solve the out of memory problem.

**Comment by Cjiangbpcs** [comment]
however, with image_size=(208, 208), a runtime error showed:

RuntimeError: simple_bind error. Arguments:
data: (1, 3, 1066, 1600)
[02:58:14] src/executor/graph_executor.cc:807: Check failed: inferred_shape == in_arg_nd.shape() ([4096,870400] vs. [4096,25088]) Inferred shape does not match shared_exec.arg_array's shape Therefore, the allocated memory for shared_exec.arg_array cannot be resued for creating NDArray of the argument fc6_weight for the current executor

@nttstar

**Comment by Cjiangbpcs** [comment]
for anybody who bumped into this as well, the pretrained model downloaded from https://www.dropbox.com/s/06zmchmq4iwj6rt/ssh-model-final.zip?dl=0, did the trick, do not use vgg16 that mentioned on the readme.md
